<?php

require_once 'vendor/autoload.php';

// Bootstrap Laravel
$app = require_once 'bootstrap/app.php';
$app->make('Illuminate\Contracts\Console\Kernel')->bootstrap();

use App\Models\AssetRequestItem;

echo "Checking asset_request_items table for return_date data...\n\n";

try {
    $items = AssetRequestItem::with(['request', 'asset'])->get();
    
    echo "Total items in asset_request_items table: " . $items->count() . "\n\n";
    
    if ($items->count() > 0) {
        echo "Item Details:\n";
        echo str_repeat("-", 80) . "\n";
        echo sprintf("%-5s %-15s %-20s %-15s %-20s\n", "ID", "Return Date", "Tracking Number", "Generated At", "Generated By");
        echo str_repeat("-", 80) . "\n";
        
        foreach ($items as $item) {
            echo sprintf(
                "%-5s %-15s %-20s %-15s %-20s\n",
                $item->id,
                $item->return_date ? $item->return_date : 'NULL',
                $item->tracking_number ? $item->tracking_number : 'NULL',
                $item->tracking_generated_at ? $item->tracking_generated_at : 'NULL',
                $item->tracking_generated_by ? $item->tracking_generated_by : 'NULL'
            );
        }
        
        echo str_repeat("-", 80) . "\n\n";
        
        // Check for items with return_date
        $itemsWithReturnDate = $items->where('return_date', '!=', null);
        echo "Items with return_date set: " . $itemsWithReturnDate->count() . "\n";
        
        // Check for items with tracking numbers
        $itemsWithTracking = $items->where('tracking_number', '!=', null);
        echo "Items with tracking_number set: " . $itemsWithTracking->count() . "\n";
        
        if ($itemsWithReturnDate->count() > 0) {
            echo "\nDetailed return_date information:\n";
            foreach ($itemsWithReturnDate as $item) {
                echo "ID: {$item->id}\n";
                echo "  Return Date: {$item->return_date}\n";
                echo "  Tracking Number: " . ($item->tracking_number ?: 'NULL') . "\n";
                echo "  Generated At: " . ($item->tracking_generated_at ?: 'NULL') . "\n";
                echo "  Generated By: " . ($item->tracking_generated_by ?: 'NULL') . "\n\n";
            }
        }
    } else {
        echo "No items found in asset_request_items table.\n";
    }
    
} catch (Exception $e) {
    echo "Error: " . $e->getMessage() . "\n";
}
