<?php

// Simple database check without Laravel
$host = 'localhost';
$dbname = 'bms_db'; // Adjust this to your database name
$username = 'root'; // Adjust this to your database username
$password = ''; // Adjust this to your database password

try {
    $pdo = new PDO("mysql:host=$host;dbname=$dbname;charset=utf8", $username, $password);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    
    echo "Connected to database successfully!\n\n";
    
    // Check table structure
    echo "Checking asset_request_items table structure:\n";
    echo str_repeat("-", 60) . "\n";
    
    $stmt = $pdo->query("DESCRIBE asset_request_items");
    $columns = $stmt->fetchAll(PDO::FETCH_ASSOC);
    
    foreach ($columns as $column) {
        echo sprintf("%-20s %-15s %-10s %-10s\n", 
            $column['Field'], 
            $column['Type'], 
            $column['Null'], 
            $column['Default'] ?? 'NULL'
        );
    }
    
    echo str_repeat("-", 60) . "\n\n";
    
    // Check data
    echo "Checking asset_request_items data:\n";
    echo str_repeat("-", 80) . "\n";
    
    $stmt = $pdo->query("SELECT id, return_date, tracking_number, tracking_generated_at, tracking_generated_by FROM asset_request_items ORDER BY id");
    $items = $stmt->fetchAll(PDO::FETCH_ASSOC);
    
    echo sprintf("%-5s %-20s %-20s %-20s %-15s\n", "ID", "Return Date", "Tracking Number", "Generated At", "Generated By");
    echo str_repeat("-", 80) . "\n";
    
    if (empty($items)) {
        echo "No records found in asset_request_items table.\n";
    } else {
        foreach ($items as $item) {
            echo sprintf("%-5s %-20s %-20s %-20s %-15s\n",
                $item['id'],
                $item['return_date'] ?: 'NULL',
                $item['tracking_number'] ?: 'NULL',
                $item['tracking_generated_at'] ?: 'NULL',
                $item['tracking_generated_by'] ?: 'NULL'
            );
        }
        
        echo str_repeat("-", 80) . "\n";
        echo "Total records: " . count($items) . "\n";
        
        // Count records with return_date
        $withReturnDate = array_filter($items, function($item) {
            return !empty($item['return_date']);
        });
        echo "Records with return_date: " . count($withReturnDate) . "\n";
        
        // Count records with tracking_number
        $withTracking = array_filter($items, function($item) {
            return !empty($item['tracking_number']);
        });
        echo "Records with tracking_number: " . count($withTracking) . "\n";
    }
    
} catch (PDOException $e) {
    echo "Database connection failed: " . $e->getMessage() . "\n";
    echo "Please check your database configuration.\n";
}
