<?php

require_once 'vendor/autoload.php';

// Bootstrap Laravel
$app = require_once 'bootstrap/app.php';
$app->make('Illuminate\Contracts\Console\Kernel')->bootstrap();

use App\Models\AssetRequestItem;

echo "Checking latest asset_request_items records...\n\n";

try {
    // Get the latest 5 records ordered by updated_at
    $items = AssetRequestItem::orderBy('updated_at', 'desc')->take(5)->get();
    
    echo "Latest 5 records (ordered by updated_at):\n";
    echo str_repeat("-", 80) . "\n";
    echo sprintf("%-5s %-20s %-20s %-20s %-15s\n", "ID", "Return Date", "Tracking Number", "Updated At", "Generated By");
    echo str_repeat("-", 80) . "\n";
    
    foreach ($items as $item) {
        echo sprintf("%-5s %-20s %-20s %-20s %-15s\n",
            $item->id,
            $item->return_date ? $item->return_date : 'NULL',
            $item->tracking_number ? $item->tracking_number : 'NULL',
            $item->updated_at,
            $item->tracking_generated_by ? $item->tracking_generated_by : 'NULL'
        );
    }
    
    echo str_repeat("-", 80) . "\n\n";
    
    // Check if there are any records with tracking numbers
    $trackingRecords = AssetRequestItem::whereNotNull('tracking_number')->get();
    echo "All records with tracking numbers: " . $trackingRecords->count() . "\n";
    
    if ($trackingRecords->count() > 0) {
        echo "\nDetailed tracking records:\n";
        echo str_repeat("-", 100) . "\n";
        foreach ($trackingRecords as $item) {
            echo "ID: {$item->id}\n";
            echo "  Return Date: " . ($item->return_date ?: 'NULL') . "\n";
            echo "  Tracking Number: " . ($item->tracking_number ?: 'NULL') . "\n";
            echo "  Generated At: " . ($item->tracking_generated_at ?: 'NULL') . "\n";
            echo "  Generated By: " . ($item->tracking_generated_by ?: 'NULL') . "\n";
            echo "  Updated At: " . $item->updated_at . "\n";
            echo str_repeat("-", 50) . "\n";
        }
    }
    
} catch (Exception $e) {
    echo "Error: " . $e->getMessage() . "\n";
}
