<?php

require_once 'vendor/autoload.php';

// Bootstrap Laravel
$app = require_once 'bootstrap/app.php';
$app->make('Illuminate\Contracts\Console\Kernel')->bootstrap();

use App\Models\Profile;

echo "🔄 Updating profiles table with complete information...\n\n";

// Update each profile by their ID
$profiles_data = [
    21 => [ // Maria Dela Cruz Santos
        'resident_id' => 'R-40-1759772852',
        'name' => 'Maria Dela Cruz Santos',
        'birth_date' => '1999-03-12',
        'age' => 25,
        'birth_place' => 'Manila, Philippines',
        'nationality' => 'Filipino',
        'civil_status' => 'Single',
        'religion' => 'Catholic',
        'relation_to_head' => 'Daughter',
        'mobile_number' => '09171234567',
        'current_address' => '123 Barangay Street, Barangay Name, City, Philippines',
        'years_in_barangay' => 5,
        'voter_status' => 'Registered',
        'voters_id_number' => 'V123456789',
        'voting_location' => 'Barangay Hall',
        'housing_type' => 'Owned',
        'head_of_family' => false,
        'household_no' => 'HH-021',
        'classified_sector' => 'Private Employee',
        'educational_attainment' => 'College Graduate',
        'occupation_type' => 'Office Worker',
        'salary_income' => '25000-35000',
        'special_categories' => json_encode(['Youth', 'Student']),
        'covid_vaccine_status' => 'Fully Vaccinated',
        'vaccine_received' => json_encode(['Sinovac', 'Pfizer']),
        'year_vaccinated' => '2021',
        'profile_completed' => true
    ],
    22 => [ // John Reyes Dizon
        'resident_id' => 'R-41-1759773397',
        'name' => 'John Reyes Dizon',
        'birth_date' => '1997-07-25',
        'age' => 27,
        'birth_place' => 'Quezon City, Philippines',
        'nationality' => 'Filipino',
        'civil_status' => 'Married',
        'religion' => 'Catholic',
        'relation_to_head' => 'Head of Family',
        'mobile_number' => '09877678876',
        'current_address' => '456 Main Avenue, Barangay Name, City, Philippines',
        'years_in_barangay' => 8,
        'voter_status' => 'Registered',
        'voters_id_number' => 'V987654321',
        'voting_location' => 'Elementary School',
        'housing_type' => 'Rented',
        'head_of_family' => true,
        'household_no' => 'HH-022',
        'classified_sector' => 'Government Employee',
        'educational_attainment' => 'College Graduate',
        'occupation_type' => 'Government Worker',
        'salary_income' => '30000-40000',
        'special_categories' => json_encode(['PWD', 'Senior Citizen']),
        'covid_vaccine_status' => 'Fully Vaccinated',
        'vaccine_received' => json_encode(['AstraZeneca', 'Moderna']),
        'year_vaccinated' => '2021',
        'profile_completed' => true
    ],
    23 => [ // Angela Ramos Bautista
        'resident_id' => 'R-42-1759773709',
        'name' => 'Angela Ramos Bautista',
        'birth_date' => '2001-01-19',
        'age' => 23,
        'birth_place' => 'Makati City, Philippines',
        'nationality' => 'Filipino',
        'civil_status' => 'Single',
        'religion' => 'Protestant',
        'relation_to_head' => 'Daughter',
        'mobile_number' => '09061430476',
        'current_address' => '789 Residential Road, Barangay Name, City, Philippines',
        'years_in_barangay' => 3,
        'voter_status' => 'Registered',
        'voters_id_number' => 'V456789123',
        'voting_location' => 'Community Center',
        'housing_type' => 'Owned',
        'head_of_family' => false,
        'household_no' => 'HH-023',
        'classified_sector' => 'Student',
        'educational_attainment' => 'College Student',
        'occupation_type' => 'Student',
        'salary_income' => '0-10000',
        'special_categories' => json_encode(['Youth', 'Student', 'Indigent']),
        'covid_vaccine_status' => 'Partially Vaccinated',
        'vaccine_received' => json_encode(['Sinovac']),
        'year_vaccinated' => '2022',
        'profile_completed' => true
    ],
    24 => [ // Carlo Mendoza Villanueva
        'resident_id' => 'R-43-1759773942',
        'name' => 'Carlo Mendoza Villanueva',
        'birth_date' => '2000-06-30',
        'age' => 24,
        'birth_place' => 'Cebu City, Philippines',
        'nationality' => 'Filipino',
        'civil_status' => 'Single',
        'religion' => 'Catholic',
        'relation_to_head' => 'Son',
        'mobile_number' => '09675679853',
        'current_address' => '321 Engineering Street, Barangay Name, City, Philippines',
        'years_in_barangay' => 4,
        'voter_status' => 'Registered',
        'voters_id_number' => 'V789123456',
        'voting_location' => 'High School',
        'housing_type' => 'Owned',
        'head_of_family' => false,
        'household_no' => 'HH-024',
        'classified_sector' => 'Private Employee',
        'educational_attainment' => 'College Graduate',
        'occupation_type' => 'Engineer',
        'salary_income' => '35000-45000',
        'special_categories' => json_encode(['Youth', 'Professional']),
        'covid_vaccine_status' => 'Fully Vaccinated',
        'vaccine_received' => json_encode(['Sinovac', 'Pfizer']),
        'year_vaccinated' => '2021',
        'profile_completed' => true
    ],
    25 => [ // Erica Santos De Guzman
        'resident_id' => 'R-44-1759774112',
        'name' => 'Erica Santos De Guzman',
        'birth_date' => '1998-04-14',
        'age' => 26,
        'birth_place' => 'Davao City, Philippines',
        'nationality' => 'Filipino',
        'civil_status' => 'Married',
        'religion' => 'Catholic',
        'relation_to_head' => 'Wife',
        'mobile_number' => '09195678901',
        'current_address' => '654 Teacher Avenue, Barangay Name, City, Philippines',
        'years_in_barangay' => 6,
        'voter_status' => 'Registered',
        'voters_id_number' => 'V321654987',
        'voting_location' => 'Elementary School',
        'housing_type' => 'Rented',
        'head_of_family' => false,
        'household_no' => 'HH-025',
        'classified_sector' => 'Government Employee',
        'educational_attainment' => 'College Graduate',
        'occupation_type' => 'Teacher',
        'salary_income' => '28000-38000',
        'special_categories' => json_encode(['Professional', 'Educator']),
        'covid_vaccine_status' => 'Fully Vaccinated',
        'vaccine_received' => json_encode(['AstraZeneca', 'Moderna']),
        'year_vaccinated' => '2021',
        'profile_completed' => true
    ],
    26 => [ // Mark Cruz Hernandez
        'resident_id' => 'R-45-1759774427',
        'name' => 'Mark Cruz Hernandez',
        'birth_date' => '1995-11-08',
        'age' => 29,
        'birth_place' => 'Iloilo City, Philippines',
        'nationality' => 'Filipino',
        'civil_status' => 'Married',
        'religion' => 'Catholic',
        'relation_to_head' => 'Head of Family',
        'mobile_number' => '09204567891',
        'current_address' => '987 Business District, Barangay Name, City, Philippines',
        'years_in_barangay' => 10,
        'voter_status' => 'Registered',
        'voters_id_number' => 'V654987321',
        'voting_location' => 'Community Center',
        'housing_type' => 'Owned',
        'head_of_family' => true,
        'household_no' => 'HH-026',
        'classified_sector' => 'Business Owner',
        'educational_attainment' => 'College Graduate',
        'occupation_type' => 'Business Owner',
        'salary_income' => '50000-70000',
        'special_categories' => json_encode(['Business Owner', 'Head of Family']),
        'covid_vaccine_status' => 'Fully Vaccinated',
        'vaccine_received' => json_encode(['Sinovac', 'Pfizer']),
        'year_vaccinated' => '2021',
        'profile_completed' => true
    ],
    27 => [ // Camille Ramos Torres
        'resident_id' => 'R-46-1759774601',
        'name' => 'Camille Ramos Torres',
        'birth_date' => '2002-02-02',
        'age' => 22,
        'birth_place' => 'Baguio City, Philippines',
        'nationality' => 'Filipino',
        'civil_status' => 'Single',
        'religion' => 'Protestant',
        'relation_to_head' => 'Daughter',
        'mobile_number' => '09351239874',
        'current_address' => '147 Student Lane, Barangay Name, City, Philippines',
        'years_in_barangay' => 2,
        'voter_status' => 'Registered',
        'voters_id_number' => 'V147258369',
        'voting_location' => 'University',
        'housing_type' => 'Owned',
        'head_of_family' => false,
        'household_no' => 'HH-027',
        'classified_sector' => 'Student',
        'educational_attainment' => 'College Student',
        'occupation_type' => 'Student',
        'salary_income' => '0-10000',
        'special_categories' => json_encode(['Youth', 'Student']),
        'covid_vaccine_status' => 'Partially Vaccinated',
        'vaccine_received' => json_encode(['Sinovac']),
        'year_vaccinated' => '2022',
        'profile_completed' => true
    ],
    28 => [ // Patrick Lopez Navarro
        'resident_id' => 'R-47-1759774872',
        'name' => 'Patrick Lopez Navarro',
        'birth_date' => '1998-09-10',
        'age' => 26,
        'birth_place' => 'Bacolod City, Philippines',
        'nationality' => 'Filipino',
        'civil_status' => 'Single',
        'religion' => 'Catholic',
        'relation_to_head' => 'Son',
        'mobile_number' => '09487561234',
        'current_address' => '258 Tech Hub, Barangay Name, City, Philippines',
        'years_in_barangay' => 5,
        'voter_status' => 'Registered',
        'voters_id_number' => 'V258369147',
        'voting_location' => 'Tech Center',
        'housing_type' => 'Rented',
        'head_of_family' => false,
        'household_no' => 'HH-028',
        'classified_sector' => 'Private Employee',
        'educational_attainment' => 'College Graduate',
        'occupation_type' => 'IT Professional',
        'salary_income' => '40000-55000',
        'special_categories' => json_encode(['Youth', 'Professional']),
        'covid_vaccine_status' => 'Fully Vaccinated',
        'vaccine_received' => json_encode(['Sinovac', 'Pfizer']),
        'year_vaccinated' => '2021',
        'profile_completed' => true
    ],
    29 => [ // Jessa Cruz Manalo
        'resident_id' => 'R-48-1759775041',
        'name' => 'Jessa Cruz Manalo',
        'birth_date' => '2000-08-04',
        'age' => 24,
        'birth_place' => 'Tacloban City, Philippines',
        'nationality' => 'Filipino',
        'civil_status' => 'Single',
        'religion' => 'Catholic',
        'relation_to_head' => 'Daughter',
        'mobile_number' => '09067893412',
        'current_address' => '369 Healthcare Street, Barangay Name, City, Philippines',
        'years_in_barangay' => 4,
        'voter_status' => 'Registered',
        'voters_id_number' => 'V369147258',
        'voting_location' => 'Hospital',
        'housing_type' => 'Owned',
        'head_of_family' => false,
        'household_no' => 'HH-029',
        'classified_sector' => 'Healthcare Worker',
        'educational_attainment' => 'College Graduate',
        'occupation_type' => 'Nurse',
        'salary_income' => '30000-45000',
        'special_categories' => json_encode(['Youth', 'Healthcare Worker']),
        'covid_vaccine_status' => 'Fully Vaccinated',
        'vaccine_received' => json_encode(['AstraZeneca', 'Moderna']),
        'year_vaccinated' => '2021',
        'profile_completed' => true
    ]
];

foreach ($profiles_data as $id => $data) {
    $profile = Profile::find($id);
    
    if ($profile) {
        echo "📝 Updating {$data['name']} (Profile ID: {$id})...\n";
        
        $profile->update([
            'birth_place' => $data['birth_place'],
            'age' => $data['age'],
            'nationality' => $data['nationality'],
            'civil_status' => $data['civil_status'],
            'religion' => $data['religion'],
            'relation_to_head' => $data['relation_to_head'],
            'current_address' => $data['current_address'],
            'years_in_barangay' => $data['years_in_barangay'],
            'voter_status' => $data['voter_status'],
            'voters_id_number' => $data['voters_id_number'],
            'voting_location' => $data['voting_location'],
            'housing_type' => $data['housing_type'],
            'head_of_family' => $data['head_of_family'],
            'household_no' => $data['household_no'],
            'classified_sector' => $data['classified_sector'],
            'educational_attainment' => $data['educational_attainment'],
            'occupation_type' => $data['occupation_type'],
            'salary_income' => $data['salary_income'],
            'business_info' => null,
            'business_type' => null,
            'business_location' => null,
            'business_outside_barangay' => false,
            'special_categories' => $data['special_categories'],
            'covid_vaccine_status' => $data['covid_vaccine_status'],
            'vaccine_received' => $data['vaccine_received'],
            'other_vaccine' => null,
            'year_vaccinated' => $data['year_vaccinated'],
            'verification_status' => 'approved',
            'denial_reason' => null,
            'profile_completed' => $data['profile_completed'],
            'my_benefits_enabled' => true
        ]);
        
        echo "✅ {$data['name']} (Profile ID: {$id}) updated successfully!\n";
        echo "   Birth Place: " . ($profile->birth_place ?? 'NULL') . "\n";
        echo "   Age: " . ($profile->age ?? 'NULL') . "\n";
        echo "   Civil Status: " . ($profile->civil_status ?? 'NULL') . "\n";
        echo "   Mobile: " . ($profile->mobile_number ?? 'NULL') . "\n";
        echo "   Profile Completed: " . ($profile->profile_completed ? 'Yes' : 'No') . "\n\n";
    } else {
        echo "❌ Profile ID {$id} not found!\n\n";
    }
}

echo "🎉 All profiles have been updated with complete information!\n";
echo "🔄 Please refresh your phpMyAdmin to see the changes.\n";
echo "📋 All NULL values should now be populated in the profiles table.\n";
